# Generated by Django 3.0.8 on 2020-09-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200916_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
